"""add is_instructor to UserDetail

Revision ID: 78d7a665bd73
Revises: e270c796f949
Create Date: 2023-03-18 10:49:24.425560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d7a665bd73'
down_revision = 'e270c796f949'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detail', sa.Column('is_instructor', sa.Boolean(), nullable=False,
                                           server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_detail', 'is_instructor')
    # ### end Alembic commands ###
