"""user detail unique fk to user

Revision ID: fb600071c3cf
Revises: 2dcdc92cdf18
Create Date: 2023-03-16 20:49:28.891354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb600071c3cf'
down_revision = '2dcdc92cdf18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_detail', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_detail', type_='unique')
    # ### end Alembic commands ###
