"""add published note and cover image to guide

Revision ID: 8fe5031c10e5
Revises: 8935f6c89dd1
Create Date: 2023-04-04 20:20:11.200594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe5031c10e5'
down_revision = '8935f6c89dd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guide', sa.Column('published', sa.Boolean(), nullable=False,
                                     server_default=sa.text('false')))
    op.add_column('guide', sa.Column('note', sa.String(length=255), nullable=True))
    op.add_column('guide', sa.Column('cover_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guide', 'cover_image')
    op.drop_column('guide', 'note')
    op.drop_column('guide', 'published')
    # ### end Alembic commands ###
