"""add socials to user detail model


Revision ID: 9b1809ef56db
Revises: fb600071c3cf
Create Date: 2023-03-17 13:38:44.995853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1809ef56db'
down_revision = 'fb600071c3cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detail', sa.Column('linkedin', sa.String(length=255), nullable=True))
    op.add_column('user_detail', sa.Column('github', sa.String(length=255), nullable=True))
    op.add_column('user_detail', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_detail', 'website')
    op.drop_column('user_detail', 'github')
    op.drop_column('user_detail', 'linkedin')
    # ### end Alembic commands ###
