"""refactor fk ondelete

Revision ID: e270c796f949
Revises: 9b1809ef56db
Create Date: 2023-03-17 13:43:24.524038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e270c796f949'
down_revision = '9b1809ef56db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_detail_profession_id_fkey', 'user_detail', type_='foreignkey')
    op.drop_constraint('user_detail_user_id_fkey', 'user_detail', type_='foreignkey')
    op.create_foreign_key(None, 'user_detail', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_detail', 'profession', ['profession_id'], ['profession_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_detail', type_='foreignkey')
    op.drop_constraint(None, 'user_detail', type_='foreignkey')
    op.create_foreign_key('user_detail_user_id_fkey', 'user_detail', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('user_detail_profession_id_fkey', 'user_detail', 'profession', ['profession_id'], ['profession_id'])
    # ### end Alembic commands ###
